# Generated by Django 3.2.22 on 2023-10-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(upload_to='static/core/img/LogoEntidad/', verbose_name='LogoArticulo'),
        ),
    ]
