# Generated by Django 3.2.22 on 2023-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(upload_to='core/static/core/img/Logo Entidad/', verbose_name='LogoArticulo'),
        ),
    ]
