# Generated by Django 3.2.22 on 2023-10-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(max_length=700),
        ),
    ]
